
const products = [
    {
      id: 1,
      name: "Buzo polar rosa",
      img: "images/buzopolarrosa.png",
      talle: "M",
      category: 'Buzos Polar',
      price: "18000",
    },
    {
      id: 2,
      name: "Buzo tejido verde y blanco",
      img: "images/buzotejidoverde.png",
      talle: "M",
      category: 'Buzos Tejidos',
      price: "30000",
    },
    {
      id: 3,
      name: "Campera impermeable amarilla",
      img: "images/camperaamarilla.png",
      talle: "S",
      category: 'Camperas Impermeables',
      price: "32000",
    },
    {
      id: 4,
      name: "Campera ecocuero",
      img: "images/camperaecocuero.png",
      talle: "M",
      category: 'Camperas Impermeables',
      price: "30000",
    },
    {
      id: 5,
      name: "Buzo polar negro",
      img: "images/camperapolarnegra.png",
      talle: "L",
      category: 'Buzos Polar',
      price: "25000",
    },
    {
      id: 6,
      name: "Buzo polar rojo",
      img: "images/camperapolarroja.png",
      talle: "M",
      category: 'Buzos Polar',
      price: "18000",
    },
    {
      id: 7,
      name: "Buzo tejido blanco",
      img: "images/camperatejidablanca.png",
      talle: "M",
      category: 'Buzos Tejidos',
      price: "30000",
    },
    {
      id: 8,
      name: "Campera impermeable rojo y negro",
      img: "images/camperitanegra.png",
      talle: "l",
      category: 'Camperas Impermeables',
      price: "23000",
    },
    {
      id: 9,
      name: "Piloto azul",
      img: "images/pilotoazul.png",
      talle: "S",
      category: 'Camperas Impermeables',
      price: "20000",
    },
    {
      id: 10,
      name: "Piloto plateado",
      img: "images/pilotoplateado.png",
      talle: "M",
      category: 'Camperas Impermeables',
      price: "23000",
    },
    {
      id: 11,
      name: "Piloto rojo",
      img: "images/pilotorojo.png",
      talle: "M",
      category: 'Camperas Impermeables',
      price: "20000",
    },
    {
      id: 12,
      name: "Buzo polar gris y azul",
      img: "images/polargrisyazul.png",
      talle: "M",
      category: 'Buzos Polar',
      price: "18000",
    },
  ];